spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/myfirstdb
    username: student
    password: 2004

  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mvc:
    hiddenmethod:
      filter:
        enabled: true